### ISSUE TITLE
Anyone tested on recent firmware versions?

### ISSUE THREAD

**Issue by richardjharris** [op1hacks/op1-fw-repacker#35]
The docs say it runs on firmware 235; latest is 243. If anyone is running it on later firmware versions it would be great to update the docs.

**Comment by DurtiCurti** [comment]
It works

**Comment by DurtiCurti** [comment]
I run it on 243 with all FXs and Synths

**Comment by richardjharris** [comment]
Can also confirm it's working fine.

**Comment by richrd** [comment]
Just a heads up someone over at the forums confirmed it to also work on firmware 245. I haven't tested yet but will at some point.

https://op-forums.com/t/op-1-fw-245/22968/7
